### ISSUE TITLE
MSigDB  Loading Error

### ISSUE THREAD

**Issue by liujilei156231** [saezlab/decoupler-py#10]
`msigdb = dc.get_resource('MSigDB')`

---------------------------------------------------------------------------
MaxRetryError                             Traceback (most recent call last)
File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/requests/adapters.py:440, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    439 if not chunked:
--> 440     resp = conn.urlopen(
    441         method=request.method,
    442         url=url,
    443         body=request.body,
    444         headers=request.headers,
    445         redirect=False,
    446         assert_same_host=False,
    447         preload_content=False,
    448         decode_content=False,
    449         retries=self.max_retries,
    450         timeout=timeout
    451     )
    453 # Send the request.
    454 else:

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/urllib3/connectionpool.py:876, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    875     log.debug("Retry: %s", url)
--> 876     return self.urlopen(
    877         method,
    878         url,
    879         body,
    880         headers,
    881         retries=retries,
    882         redirect=redirect,
    883         assert_same_host=assert_same_host,
    884         timeout=timeout,
    885         pool_timeout=pool_timeout,
    886         release_conn=release_conn,
    887         chunked=chunked,
    888         body_pos=body_pos,
    889         **response_kw
    890     )
    892 return response

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/urllib3/connectionpool.py:876, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    875     log.debug("Retry: %s", url)
--> 876     return self.urlopen(
    877         method,
    878         url,
    879         body,
    880         headers,
    881         retries=retries,
    882         redirect=redirect,
    883         assert_same_host=assert_same_host,
    884         timeout=timeout,
    885         pool_timeout=pool_timeout,
    886         release_conn=release_conn,
    887         chunked=chunked,
    888         body_pos=body_pos,
    889         **response_kw
    890     )
    892 return response

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/urllib3/connectionpool.py:876, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    875     log.debug("Retry: %s", url)
--> 876     return self.urlopen(
    877         method,
    878         url,
    879         body,
    880         headers,
    881         retries=retries,
    882         redirect=redirect,
    883         assert_same_host=assert_same_host,
    884         timeout=timeout,
    885         pool_timeout=pool_timeout,
    886         release_conn=release_conn,
    887         chunked=chunked,
    888         body_pos=body_pos,
    889         **response_kw
    890     )
    892 return response

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/urllib3/connectionpool.py:866, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    865 try:
--> 866     retries = retries.increment(method, url, response=response, _pool=self)
    867 except MaxRetryError:

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/urllib3/util/retry.py:592, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    591 if new_retry.is_exhausted():
--> 592     raise MaxRetryError(_pool, url, error or ResponseError(cause))
    594 log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /annotations?entity_types=protein&format=tsv&resources=MSigDB (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

RetryError                                Traceback (most recent call last)
Input In [37], in <cell line: 1>()
----> 1 msigdb = dc.get_resource('MSigDB')
      2 msigdb

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/decoupler/omnip.py:82, in get_resource(name)
     78 assert name in resources, msg.format(name)
     80 op = check_if_omnipath()
---> 82 df = op.requests.Annotations.get(resources=name, entity_type="protein")
     83 df = df.set_index(['record_id', 'uniprot', 'genesymbol', 'entity_type', 'source', 'label'])
     84 df = df.unstack('label').droplevel(axis=1, level=0)

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/omnipath/_core/requests/_utils.py:104, in _inject_api_method.<locals>.wrapper(wrapped, _instance, args, kwargs)
    102 @wrapt.decorator(adapter=wrapt.adapter_factory(argspec_factory))
    103 def wrapper(wrapped, _instance, args, kwargs):
--> 104     return wrapped(*args, **kwargs)

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/omnipath/_core/requests/_annotations.py:114, in Annotations.get(cls, proteins, resources, force_full_download, **kwargs)
    100     return pd.concat(
    101         [
    102             inst._get(
   (...)
    109         ]
    110     )
    112 logging.info(f"Downloading annotations for all proteins from {res_info}")
--> 114 return inst._get(proteins=None, resources=resources, **kwargs)

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/omnipath/_core/requests/_request.py:107, in OmnipathRequestABC._get(self, **kwargs)
    104 kwargs = self._validate_params(kwargs)
    105 kwargs = self._finalize_params(kwargs)
--> 107 res = self._downloader.maybe_download(
    108     self._query_type.endpoint, params=kwargs, callback=callback, is_final=False
    109 )
    111 if self._downloader._options.convert_dtypes:
    112     res = self._convert_dtypes(res)

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/omnipath/_core/downloader/_downloader.py:128, in Downloader.maybe_download(self, url, callback, params, cache, is_final, **_)
    126     res = self._options.cache[key]
    127 else:
--> 128     res = callback(self._download(req))
    129     if cache:
    130         logging.debug(f"Caching result to `{self._options.cache}[{key!r}]`")

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/omnipath/_core/downloader/_downloader.py:154, in Downloader._download(self, req)
    151 logging.info(f"Downloading data from `{req.url}`")
    153 handle = BytesIO()
--> 154 with self._session.send(
    155     req, stream=True, timeout=self._options.timeout
    156 ) as resp:
    157     resp.raise_for_status()
    158     total = resp.headers.get("content-length", None)

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/requests/sessions.py:645, in Session.send(self, request, **kwargs)
    642 start = preferred_clock()
    644 # Send the request
--> 645 r = adapter.send(request, **kwargs)
    647 # Total elapsed time of the request (approximately)
    648 elapsed = preferred_clock() - start

File ~/miniconda3/envs/scvi-env/lib/python3.9/site-packages/requests/adapters.py:510, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    507         raise ConnectTimeout(e, request=request)
    509 if isinstance(e.reason, ResponseError):
--> 510     raise RetryError(e, request=request)
    512 if isinstance(e.reason, _ProxyError):
    513     raise ProxyError(e, request=request)

RetryError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /annotations?entity_types=protein&format=tsv&resources=MSigDB (Caused by ResponseError('too many 500 error responses'))

**Comment by deeenes** [comment]
Hello,

This request failed once over the past days, and the error page itself has been propagated to the proxy cache. Now I deleted the wrong cache item, so it should work from now. I will fix later the issue that error pages shouldn't be saved in cache.

Apologies for the inconvenience!

Best,

Denes

**Comment by liujilei156231** [comment]
Thanks @deeenes @PauBadiaM ,the errror has been solved!

**Comment by adamklie** [comment]
Hello!

First off, just want to say thanks for developing this awesome package!.

I'm running into the same error when attempting to load msigdb

```python
msigdb = dc.get_resource('MSigDB')

One long stack trace later...

File ~/opt/miniconda3/envs/scverse-lite-py38/lib/python3.8/site-packages/requests/adapters.py:556, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    553         raise ConnectTimeout(e, request=request)
    555 if isinstance(e.reason, ResponseError):
--> 556     raise RetryError(e, request=request)
    558 if isinstance(e.reason, _ProxyError):
    559     raise ProxyError(e, request=request)

RetryError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /annotations?entity_types=protein&format=tsv&resources=MSigDB (Caused by ResponseError('too many 500 error responses'))
```

I tried deleting items in my `$HOME/.cache/omnipath/*` but still running into this. Not essential to get working but wanted to run it by the team! Thanks!

**Comment by PauBadiaM** [comment]
Hi @adamklie 

Thanks for using the package! ;) 
It seems like MSigDB might still have problems, @deeenes could you take a look?

**Comment by PauBadiaM** [comment]
Hi @adamklie 

It was a  transient error in the server due to memory issues. I tested it now and it works. I will close this issue now but feel free to open it again in case it stops working.

**Comment by adamklie** [comment]
It works and I now have MSigDB! Thanks!
